#!/bin/sh
# vi: ts=4 noexpandtab

# the intent of this script is to be inserted into the instance
# it will then live in the /var/lib/cloud/data/scripts dir
# but will not do anything unless 'password' is seeded via template
# or given on command line.
#
# we allow it given on the command line so it can be used later
# potentially it could be utilized to enable password login as a
# fix for LP: #654944

user=""
pass=""

# these wont be substituted by django template.
pstr="{ password }"
ustr="{ user }"

# test weather or not a substitution was done on user, password
# if it was, set user and pass
[ '{{ user }}' = "{${ustr}}" ] || user='{{ user }}'
[ '{{ password }}' = "{${pstr}}" ] || pass='{{ password|safe }}'

user=${1:-${user}}
pass=${2:-${pass}}

# if no password was given, we dont do anything
if [ -z "${pass}" -o "${pass}" = "None" ]; then
	exit 0
fi

fail() { echo "$@" 1>&2; echo "$@" >> /var/log/instance-testing; exit 1; }

pa_s="\(PasswordAuthentication[[:space:]]\+\)"

echo "${user}:${pass}" | chpasswd ||
	fail "failed to chpasswd for ${user}"
sed -i "s,${pa_s}no,\1yes," /etc/ssh/sshd_config ||
	fail "failed to switch chpasswd for ${user}"
restart ssh ||
	fail "failed to restart ssh"

{% if debug %}
# instance testing
expires=$(passwd --status ubuntu |awk '{print $5}')
echo "Password expires in $expires days" >> /var/log/instance-testing
{% endif %}

exit 0
