#!/bin/bash
f="/etc/update-motd.d/01-personal-hello"
cat > "${f}" <<"MOTD_END"
#!/bin/sh
LAUNCH_TIME="{{ launch_time }}"
term=$(date --date "${LAUNCH_TIME} + 55 minutes")
cat <<EOF
Hello {{ launchpad_id }}, welcome to the Cloud!
  This instance will terminate around ${term}"
EOF
MOTD_END
chmod 755 "${f}"
